name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'V*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install build tools
      run: python -m pip install --upgrade pip build twine
    
    - name: Build package
      run: python -m build  # This reads pyproject.toml
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
  